@startuml

class auth_user {
  +int id
  +varchar password
  +datetime last_login
  +tinyint is_superuser
  +varchar username
  +varchar first_name
  +varchar last_name
  +varchar email
  +tinyint is_staff
  +tinyint is_active
  +datetime date_joined
  +check_password(): bool
  +get_full_name(): str
}

class main_usernotificationpreference {
  +bigint id
  +tinyint news_notifications
  +tinyint email_notifications
  +tinyint site_notifications
  +int user_id
  +get_preferences(): string
  +update_preferences(): void
}

class main_userprofile {
  +bigint id
  +varchar profile_image
  +int user_id
  +get_profile(): string
  +update_profile_image(): void
}

class main_signin {
  +bigint id
  +date last_sign_in_date
  +int sign_in_count
  +int consecutive_sign_in_count
  +int user_id
  +record_sign_in(): void
}

main_usernotificationpreference "0..1" -- "1" auth_user : "user_id"
main_userprofile "0..1" -- "1" auth_user : "user_id"
main_signin "0..*" --> "1" auth_user : "user_id"

@enduml
